Zmień czcionkę na tą z odrabiamy i zwiększ jej rozmiar dla zwiększenia wydoczności
doteq/odrabiamy-bot pull request #5
Opened 2022-02-02 23:07 UTC by m1chaelbarry

2022-02-06 15:22 UTC, doteq requested changes
Nie mam za bardzo jak przetestować, bo nie mam konta, ale sam kod wygląda dobrze tylko prosiłbym o poprawienie tych 2 rzeczy.
 
 Dzięki za pr, mi się szczerze znudziła walka z puppeteerem <3

2022-02-06 15:22 UTC, doteq commented on src/odrabiamy.ts
> +        console.log(decoded_solution)
Usuń console.log, żeby nie zaśmiecać konsoli zadaniami

2022-02-06 15:22 UTC, doteq commented on src/odrabiamy.ts
> +        await loaded
Wiem że czekanie na stronę aż się załaduje w puppeteer jest dziwne, ale nie można było wyżej w deklaracji dać await?
``` ts
const loaded = await page.waitForNavigation({waitUntil: 'load'});
await page.setContent(decoded_solution, {waitUntil: 'networkidle0'});
```
oraz może dodatkowo zamienić te linie miejscami?

2022-02-06 15:34 UTC, m1chaelbarry commented on src/odrabiamy.ts
> +        await loaded
teraz powinno byc git

2022-02-06 19:56 UTC, doteq approved these changes

2022-02-06 19:57 UTC, merged

2022-02-15 12:39 UTC, barkowiczn3 commented
skąd moge wziaść auth z odrabiamy???

2022-02-15 13:19 UTC, m1chaelbarry commented
>https://github.com/doteq/odrabiamy-bot/pull/5#issuecomment-1040225297
https://github.com/doteq/odrabiamy-bot/issues/1#issuecomment-962601416